[workspace]
resolver = "2"
members = ["crates/mdrv-db", "crates/mdrv-db-napi"]

[workspace.package]
edition = "2021"
version = "0.3.0"
license = "MIT"
repository = "https://github.com/mdrv/mdrv-db"

[workspace.dependencies]
fjall = "3.1"
serde = { version = "1", features = ["derive"] }
postcard = { version = "1", features = ["alloc"] }
serde_json = "1"
blake3 = "1"
sha2 = "0.10"
thiserror = "2"
regex = "1"
turso = "0.7"
clap = { version = "4", features = ["derive"] }
clap_complete = "4"
carapace_spec_clap = "1"
toml = "0.9"
napi = { version = "3", default-features = false, features = ["napi8", "tokio_rt", "async", "serde-json"] }
napi-derive = "3"
napi-build = "2"
tokio = { version = "1", features = ["rt"] }

[profile.release]
lto = "thin"
strip = "symbols"
